### ISSUE TITLE
Please specify the license unambiguously

### ISSUE THREAD

**Issue by tarsius** [dotemacs/omniref.el#6]
"BSD" can refer to any one of multiple related licenses. Please change the value of `License` to `BSD-N-clause`, where `N` is one of 4, 3 or 2. For additional information see https://en.wikipedia.org/wiki/BSD_licenses. You might also want to copy the full text of the chosen license into the library header.

Thanks!

**Comment by dotemacs** [comment]
Hi @tarsius 

valid points. I'll get to it this weekend. 

Thanks

**Comment by tarsius** [comment]
Thanks!

**Comment by tarsius** [comment]
Friendly ping!
